# Python-Julianbeggs
BINANCE_API_KEY = 'P3Z34LrK3ucYM9FwhQh2IQKQTlGOTqXJ1notQvSJs59HvvQ5XZ2Q4630TcT60bfJ'
BINANCE_SECRET_KEY = 'feIm62CH8Xk9OkRed1amPUSOvF0uJJhFrlWqyeUL1ZAtDHWEr5TWZKCZjahpUNOt'

# Trading config
EXCHANGE = 'binance'
SYMBOL = 'ETH/BUSD'
TIMEFRAME = '1m'